import { Metadata } from "next";
import { Bitter } from "next/font/google";
import ClientRouter from "../components/ClientRouter"; // Importa el ClientRouter

const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Please Cat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={bitter.className}>
        <ClientRouter children={undefined} /> {/* Renderiza el ClientRouter */}
      </body>
    </html>
  );
}