// app/layout.tsx (Server Component)
import { Metadata } from "next";
import { Bitter } from "next/font/google";


const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Please Cat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
    <meta charSet="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={bitter.className}>
       {children}
      </body>
      </head>
    </html>
  );
}